### ISSUE TITLE
How to customize theme and layout / sanitize back ticks?

### ISSUE THREAD

**Issue by zeluspudding** [idyll-lang/idyll-embed#2]
First off, Idyll is amazing! Very nice work and kudos to everyone who's breathed life into it. I'm really excited to start using it. I have managed to get an example from the Idyll gallery working at [this codepen](https://codepen.io/aagostini/pen/LYYvdqR?editors=1000). It's soo cool!

I have two questions:
1. How do I set the `layout`, `theme`, and perhaps most importantly, the `datasets` parameters for embedded Idyll?
2. Assuming I wanted to make a simple editor [like the one found here](https://idyll-lang.org/editor), I would have to pass Idyll a string of Idyll Markup. However, those strings, as I am finding, have many back ticks ( ` ) that need escaping. Does Idyll accept a string with unescaped back ticks? Or do I have to escape them somehow before passing the string to be rendered?

thanks in advance,

**Comment by zeluspudding** [comment]
Wondering if these issues I'm having are simply due to `idyll-embed.min.js` being out of date (and thus not having `theme` options...

**Comment by mathisonian** [comment]
@zeluspudding thanks for the kind words and interest in the project! That's the first time I've seen an example running on codepen, pretty cool 😄 

I think you're right about the `dist` version being out of date. It looks like the `idyll-document` dependency needs to be upgraded and then we should cut a new release. I'll make a note that we need to add updating this package as a task each time a new version is released. 

As for the backticks, you shouldn't need to escape them unless you are writing Idyll markup inside of a JavaScript file. If you are retrieving the string of Idyll markup from e.g. a `TextArea` or similar, you shouldn't need to do special escaping - see e.g. [the source for the editor that you referenced](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-docs/components/editor/index.js#L32-L62), vs. [this case](https://github.com/mathisonian/mathisonian.github.io/blob/master/pages/writing/apparatus.js#L17-L50) where idyll written inside of a JS file and _does_ need to be escaped.
Are you hitting errors related to backticks?

**Comment by zeluspudding** [comment]
Oh, excellent! As long as retrieving the string from a `TextArea` works then it should work in my application. I'll report back otherwise. 

As for updating the distro, when abouts does that happen?.. curious to know when I'll be able to mount data.

Thanks again (also, I just donated to the project, keep up the great work!)!

**Comment by mathisonian** [comment]
I just compiled and pushed an updated version with the latest version of `idyll-document` and friends, so it should be good to use. 

Here is the HTML I tested with:

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <style>
      html, body {
        padding: 0;
        margin: 0;
      }

      .idyll-root {
        padding: 0 !important;
      }
    </style>
  </head>

  <body>
    <script src="dist/idyll-embed.min.js"></script>
    <script>
      // Create a new div where Idyll will inject content.
      var div = document.createElement('div');
      document.body.appendChild(div);

      // Get your markup.
      var idyllMarkup = `
      [Header title:"Hello World" author:"Matthew Conlen" fullWidth:true  /]

      Normal paragraph text.

      ## Subheader

      `;

      // This will make all standard components available by default.
      // To add additional components, register them.
      // Idyll.registerComponent('ComponentName', Component);

      // Instantiate the Idyll runtime.
      Idyll.render(idyllMarkup, div, {
        theme: 'default',
        layout: 'centered',
        injectThemeCSS: true,
        injectLayoutCSS: true
      });
    </script>
  </body>
</html>
```

Note two things:

- The `injectThemeCSS` and `injectLayoutCSS` properties. You need to opt-in to tell idyll to actually modify the page's CSS. 
- It needed an additional `.idyll-root` CSS property to look exactly as expected. It would be nice if we could clean up the styles to eliminate the need for this. 

<img width="1552" alt="Screen Shot 2019-11-26 at 3 18 17 PM" src="https://user-images.githubusercontent.com/1074773/69680529-011ffd80-1060-11ea-8a4d-b54191f61977.png">

> Thanks again (also, I just donated to the project, keep up the great work!)!

🤗 ✨ Thank you! I'll be sending out stickers to the latest supporters next week, so look out for an email regarding that.

**Comment by zeluspudding** [comment]
Sweet!

**Comment by mathisonian** [comment]
Hey @zeluspudding - it appears that I didn't get your contact info thru opencollective. Could you shoot me an email at mconlen@cs.washington.edu so I can get an address to send stickers?
